export default {
    COLORS__ADD: 'COLORS__ADD',
    COLORS__REMOVE: 'COLORS__REMOVE',
    COLORS__DEFAULT: 'COLORS__DEFAULT',

    RATING__CHANGE: 'RATING__CHANGE',

    PRICE_RANGE__CHANGE: 'PRICE_RANGE__CHANGE',
    PRICE_RANGE__DEFAULT: 'PRICE_RANGE__DEFAULT',

    SEASON__CHANGE_CHECK: 'SEASON__CHANGE_CHECK',
    SEASON__DEFAULT: 'SEASON__DEFAULT',

    PRODUCT__GETBYID: 'PRODUCT__GETBYID',
    PRODUCT__GETBYID__SUCCESS: 'PRODUCT__GETBYID__SUCCESS',
    PRODUCT__GETBYID__ERROR: 'PRODUCT__GETBYID__ERROR',

    CART__ADD: 'CART__ADD',
    CART__REMOVE: 'CART__REMOVE',
}
