export default {
    COLORS__ADD: 'COLORS__ADD',
    COLORS__REMOVE: 'COLORS__REMOVE',
    COLORS__DEFAULT: 'COLORS__DEFAULT',

    RATING__CHANGE: 'RATING__CHANGE',

    PRICE_RANGE__CHANGE: 'PRICE_RANGE__CHANGE',
    PRICE_RANGE__DEFAULT: 'PRICE_RANGE__DEFAULT',

    SEASON__CHANGE_CHECK: 'SEASON__CHANGE_CHECK',
    SEASON__DEFAULT: 'SEASON__DEFAULT',
}